---
title: "Stat403_HW6"
output: html_document
---

```{r}
x  <- c(-0.327, -0.849,  5.049, -1.060, -0.680,  1.925, -0.450, -1.529,  0.759,
       1.323, 1.117, -0.238,  0.259, -2.064, -0.069)
y <- c(1.472, -0.455, -0.902, -0.340,  1.316, -0.702,  0.657, -0.084, -0.190,
       0.027, -0.654, -0.290)
```

```{r}
#1
set.seed(111)

B = 10000
XX <- numeric(B)
YY <- numeric(B)
for(i in 1:B){
  XX[i] = sd(rnorm(length(x)))
  YY[i] = sd(rnorm(length(y)))
}
(pvalue = mean(XX/YY>2.236))
sqrt(pvalue*(1-pvalue)/B)
```

```{r}
#2
set.seed(111)

B = 10000
XX <- numeric(B)
YY <- numeric(B)
for(i in 1:B){
  XX[i] = sd(rnorm(length(x),0,4))
  YY[i] = sd(rnorm(length(y)))
}
(pvalue = mean(XX/YY <= 2.236))
sqrt(pvalue*(1-pvalue)/B)
```

```{r}
#3
set.seed(111)

B = 5000
T_BT = rep(NA, B)
for(i_BT in 1:B){
  xx = sample(length(x),length(x),replace=T)
  X_BT = x[xx]
  X_BT
  yy = sample(length(y),length(y),replace=T)
  Y_BT = y[yy]
  Y_BT
  T_BT[i_BT] = sd(X_BT)/sd(Y_BT)
}


T_true <- sd(x)/sd(y)
hist(T_BT, col="skyblue")
abline(v=T_true, lwd=3, col="red")


quantile(T_BT, c(0.025,0.975))
```

```{r}
#4
set.seed(111)
n = length(x) + length(y)
data_pull = c(x, y)
diff_T <- sd(x) / sd(y)
N_per = 10000
diff_T_per = rep(NA, N_per)
for(i_per in 1:N_per){
  w_per = sample(n, n, replace=F)
  data_per = data_pull[w_per]
  x_new = data_per[1:length(x)]
  y_new = data_per[(length(x)+1):n]
  T_new = sd(x_new)/sd(y_new)
  diff_T_per[i_per] = T_new
}

# this is the p-value of permutation test;  >=, and N_per+1
(length(which(diff_T_per >= diff_T))+1)/(N_per+1)
```